### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by byAmmerix** [SwiftKit/Cuckoo#1]
Is it possible to use Cuckoo with Carthage?

**Comment by TadeasKriz** [comment]
Hey, I just tried adding:
`github "SwiftKit/Cuckoo"` to a Cartfile and then `carthage update`. It did build Cuckoo.framework properly. Could you please try it in you project and let me know if it works when added to xcode?

**Comment by byAmmerix** [comment]
@TadeasKriz I get the following error when executing
 ```cuckoo generate -version 0.1.0 -testable CuckooDemo -output ./Generated Greeter.swift```:
```Unrecognized arguments: -irnveso, -besalt, -outp```

I also adapted the run script phase:
```
# Find the installed Cuckoo version 
CUCKOO_VERSION=$(grep '\- Cuckoo' "$PROJECT_DIR/Cartfile.resolved" | grep -o '[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}')
```

**Comment by TadeasKriz** [comment]
I am so sorry, I messed up the readme. It has to be `--runtime` instead of the `-version` and `--testable` instead of just `-testable` and `--output` instead of `-output`. Please try it and let me know. I'm fixing the readme right away.

**Comment by byAmmerix** [comment]
Thanks everything works now 👌
I recommend to add an instruction to use Cuckoo with Carthage to the readme.

**Comment by TadeasKriz** [comment]
Awesome! So this:
```
# Find the installed Cuckoo version 
CUCKOO_VERSION=$(grep '\- Cuckoo' "$PROJECT_DIR/Cartfile.resolved" | grep -o '[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}')
```

will find the version of Cuckoo in project using Carthage?

**Comment by ammerzon** [comment]
Sorry my fault. The parameter ```'\- Cuckoo'``` was wrong.

Corrected version:
```
# Find the installed Cuckoo version 
CUCKOO_VERSION=$(grep 'Cuckoo' "$PROJECT_DIR/Cartfile.resolved" | grep -o '[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}')
```
