### ISSUE TITLE
GeneratedMocks is empty

### ISSUE THREAD

**Issue by oliverfoggin** [SwiftKit/Cuckoo#10]
I have followed the README but when I run the tests the GeneratedMocks file is empty.

I'm not sure where to go from here. How do I specify which protocols Cuckoo should mock?

Thanks

**Comment by TadeasKriz** [comment]
Hi, in the run script you have to specify files for which mocks will be generated (It is at the end of the script, "FileName1.swift, FileName2.swift" etc.

All protocols and classes in those files you select should have helper classes generated for them into the GeneratedMocks file. If not, let me know, there might be a bug :)

Once you have those helper classes generated, you can start using them right away in your tests.

**Comment by oliverfoggin** [comment]
Ah, I'm an idiot. Didn't spot the comment in the script file :D

Thanks, it has generated code now.

**Comment by TadeasKriz** [comment]
No problem :) Glad you got it working 👍
