### ISSUE TITLE
Prevent name clashes with mocked method parameter names

### ISSUE THREAD

**Issue by rbeeger** [SwiftKit/Cuckoo#102]
Each mock class has an instance variable `manager`. In a class that implements `CLLocationManagerDelegate` I have methods like `func locationManager(_ manager: CLLocationManager, didExitRegion region: CLRegion)`.
The generated mock does not compile because `manager` in the overrridden methods is `CLLocationManager` which has no `call` and `verify` methods.

Cuckoo should use names for its generated code that do not clash with names in the mocked class. `cuckoo_manager` or something like that could be used.

**Comment by TadeasKriz** [comment]
@rbeeger Great catch! That's definitely something we need to fix.
