### ISSUE TITLE
Script invocation error: Cannot capture 'watcher' before it is declared

### ISSUE THREAD

**Issue by makeready** [SwiftKit/Cuckoo#121]
Hello,

We're trying to run the script to build the mocks as per the instructions, but we're running into the same core Swift errors regardless of how we use / escape environment variables to construct the script.

(Running this on Xcode 8.3.2 with Swift 3.1)

Here's our script:

`OUTPUT_FILE="$PROJECT_DIR/YrooTests/GeneratedMocks.swift"
INPUT_DIR="$PROJECT_DIR/Yroo"
${PODS_ROOT}/Cuckoo/run generate --testable "Yroo" --output "${OUTPUT_FILE}" "${INPUT_DIR}/Auth.swift"`

Executing that script raises 3 errors and 2 warnings:

`/Users/makeready/work/yroo-ios/Pods/Cuckoo/Generator/Dependencies/FileKit/Sources/Path.swift:1074:17: warning: 'ExpressibleByStringInterpolation' is deprecated: it will be replaced or redesigned in Swift 4.0.  Instead of conforming to 'ExpressibleByStringInterpolation', consider adding an 'init(_:String)'
extension Path: ExpressibleByStringInterpolation {
                ^
/Users/makeready/work/yroo-ios/Pods/Cuckoo/Generator/Dependencies/FileKit/Sources/FileSystemWatcher.swift:48:17: error: cannot capture 'watcher' before it is declared
                watcher.lastEventId = lastEventId
                ^
/Users/makeready/work/yroo-ios/Pods/Cuckoo/Generator/Dependencies/FileKit/Sources/FileSystemWatcher.swift:54:13: note: 'watcher' declared here
        let watcher: FileSystemWatcher = unsafeBitCast(contextInfo, to: FileSystemWatcher.self)
            ^
/Users/makeready/work/yroo-ios/Pods/Cuckoo/Generator/Dependencies/FileKit/Sources/TextFile.swift:202:21: warning: conditional downcast from 'NSString?' to 'String' is a bridging conversion; did you mean to use 'as'?
        return line as? String
               ~~~~ ^~~ ~~~~~~
                    as        ?

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
mv: rename Build/cuckoo_generator.app to cuckoo_generator.app: No such file or directory
./Pods/Cuckoo/run: line 22: ((: i<: syntax error: operand expected (error token is "<")
xargs: ./Pods/Cuckoo/Generator/cuckoo_generator.app/Contents/MacOS/cuckoo_generator: No such file or directory`

Thanks!

**Comment by TadeasKriz** [comment]
Hi, could you give our `stencil` branch a try? It should support Swift 3.1. Let me know if it works, thanks!

**Comment by makeready** [comment]
That did the trick. Thanks!
