### ISSUE TITLE
Allow to reset stubbing.

### ISSUE THREAD

**Issue by FilipDolnik** [SwiftKit/Cuckoo#33]

**Comment by TadeasKriz** [comment]
Is this a good idea? Won't it make it more difficult to reason about?

**Comment by FilipDolnik** [comment]
I used it sometimes in Mockito. For example when I set the stubbing in setUp and then want to create one test without this settings.

**Comment by TadeasKriz** [comment]
Ok. This should be easy to add.

**Comment by FilipDolnik** [comment]
Implemented in 0.6.0.
