### ISSUE TITLE
Example with equalTo

### ISSUE THREAD

**Issue by adamszeptycki** [SwiftKit/Cuckoo#4]
Hey,
Could you provide example of mock that will expect specific value of argument. I know that there is an example with String in readme, but for it doesn't work for me with any other class/struct.

**Comment by TadeasKriz** [comment]
By default `equalTo` can be used three ways:

1. Having the type you want to check implement `Equatable`. Then Cuckoo will use Swift's `==` operator function to compare the given object with the argument.

2. Having the type you want to check be a class. Then Cuckoo will use Swift's `===` (object identity) operator function to compare the instance of given object with the argument. This means it will check if both of them are identical instances.

3. You can pass an equality function of your own as a second parameter (or a trailing closure) to the `equalTo` function. That closure would have two parameters and you need to return `true` or `false` to indicate if the given object is equal to the argument. This allows you to implement your own comparing logic without the hassle of implementing `Equatable`.

There are more complex options like implementing [`Matchable`](https://github.com/SwiftKit/Cuckoo/blob/master/Source/Matchable.swift), but you should not need to do it.

Let me know if I can help more and see [MatcherFunctions.swift](https://github.com/SwiftKit/Cuckoo/blob/master/Source/MatcherFunctions.swift) for the list of all builtin helper functions.

**Comment by adamszeptycki** [comment]
>Having the type you want to check implement Equatable. Then Cuckoo will use Swift's == operator function to compare the given object with the argument.

For me it works only with build in types.

And how would you approach comparing collection types.


And Thx for the library ;)

**Comment by TadeasKriz** [comment]
You have to use the function `equalTo` (or the short `eq`). For example `when(anObject.someMethod(eq(yourEquatable)).thenReturn(...)`.

Collection types, great question. I wanted to implement something like: `extension SequenceType: Matchable where Generator.Element: Equatable { ... }` however that cannot be done in the current version of Swift. I wanted to add `equalTo` for SequenceType, but I forgot to do it. I might be able to add it by the end of the week though :)

Thanks for using it!

**Comment by adamszeptycki** [comment]
It would be awesome to get that collection comparison.

I thing this will be my favourite mocking framework :P you will see me here more often. Are you open for PR?

**Comment by TadeasKriz** [comment]
Sure, PR are always welcome :) Especially tests and documentation need some love :)
