### ISSUE TITLE
Problems with project name containing spaces

### ISSUE THREAD

**Issue by michary** [SwiftKit/Cuckoo#50]
Hi guys,

there might be some problems, if the project name contains spaces.

Cuckoo generated this file in the project folder:
```
// MARK: - Mocks generated from file: Scrum at 2016-07-16 06:42:52 +0000


import Cuckoo
@testable import Scrum
```

The project name is "Scrum Poker"

Greets
Michael

**Comment by TadeasKriz** [comment]
Nice catch! Is this all the code that gets generated into the file or is it otherwise working but the `@testable import Scrum` is wrong?

**Comment by michary** [comment]
The generated filename is only "Scrum"
According to the script it should be "Scrum PokerTests/GeneratedMocks.swift"

The correct import is "@testable import Scrum_Poker"

**Comment by FilipDolnik** [comment]
To solve the issue with the path just replace `--output ${OUTPUT_FILE}` with `--output "${OUTPUT_FILE}"` (put it in quotes). Problem with @testable will be fixed in next release. For now you can type it manually: `--testable Scrum_Poker`.
