### ISSUE TITLE
Can I mock view controllers?

### ISSUE THREAD

**Issue by wowbroforce** [SwiftKit/Cuckoo#52]
Hi.
I've tried to use this pod for mocking view controllers but I got a lot of errors in generated mock file. For example, if I create a subclass of UIViewController, I will have two errors: 
```
Initializer does not override a designated initializer from its superclass
```
```
'required' initializer 'init(coder:)' must be provided by subclass of 'DetailsRegistrationController'
```
And I want to clarify - do I need to write some additional code to get things work or it is currently impossible?

**Comment by TadeasKriz** [comment]
@wowbroforce Hi, please try the new release 0.7.0, it might fix the problem. However it will not work if your controller has no declared initializers. We are currently unable to detect the grandparent declarations.
