### ISSUE TITLE
custom initializers causing errors in generated mock file

### ISSUE THREAD

**Issue by bobbelkl** [SwiftKit/Cuckoo#54]
following code
```
  init(userName: String, password: String)  {
    self.userName = userName
    self.password = password
    self.sessionId = (self.userName+self.password).hash.description
  }
```
generates this:
```
    override init(userName userName: String, password: String) {
        return manager.call("init(userName:String, password:String)", parameters: (userName: userName, password: password), original: observed.map { o in return { (userName userName: String, password: String) in o.init(userName: userName, password: password) } })
    }
```

removing the double designation doesn't help

**Comment by krin-san** [comment]
@bobbelkl, I experienced the same issue: https://github.com/SwiftKit/Cuckoo/issues/6#issuecomment-241656839
Let's keep this ticket opened to track a code generator issue progress.

**Comment by TadeasKriz** [comment]
Hey guys, I just merged the overhaul PR, but I would like to wait with the release until we fix these issues. However you can give it a try, just add the CocoaPods dependency as a git repository, targeting the `master` branch. We have made a lot of changes and also merged the runtime and generator repository for easier updates and usage.

**Comment by krin-san** [comment]
@TadeasKriz, I re-generated mocks file for the following class using **Cuckoo** from the commit c9fce39792fc5dbdfefc8ae0de44ff4ba317f01b. Still no success with generated closure.
```swift
class MyClass {
    func objects(byFilter filter: String) -> String {
        return ""
    }
}
```
```swift
class MockMyClass: MyClass, Cuckoo.Mock {
    typealias Stubbing = __StubbingProxy_MyClass
    typealias Verification = __VerificationProxy_MyClass
    let manager = Cuckoo.MockManager()
    
    private var observed: MyClass?
    
    required override init() {
    }
    
    required init(spyOn victim: MyClass) {
        observed = victim
    }
    
    override func objects(byFilter filter: String) -> String {
        return manager.call("objects(byFilter: String) -> String", parameters: (filter), original: observed.map { o in return { (byFilter filter: String) -> String in o.objects(byFilter: filter) } })
    }
    
    struct __StubbingProxy_MyClass: Cuckoo.StubbingProxy {
        ...
    }
    
    struct __VerificationProxy_MyClass: Cuckoo.VerificationProxy {
        ...
    }
}
```
The following declaration is not a valid closure syntax:
```swift
(byFilter filter: String) -> String
```

**Comment by TadeasKriz** [comment]
@bobbelkl @krin-san Hey guys, please give it a try. Use commit `c7dd503669f1c1cf799aba5d2cfa9b93af64313f` in your Podfile and if it works as expected, we'll release a new version :) Thanks.

**Comment by bobbelkl** [comment]
Works for me!
All initializers are ignored, as they should.

Thanks!

**Comment by TadeasKriz** [comment]
@bobbelkl Awesome!

**Comment by bobbelkl** [comment]
Ok, found some issues.
I was mistaken stating the custom initializers are ignored, instead they become the default initializers, additionally the spyOn initializer is gone.

In my eyes the more elegant solution would be ignoring the custom initializers in classes. If you really need them you can still use "spyOn".

**Comment by TadeasKriz** [comment]
We can't ignore custom initializers, because when initializing the mock, we have to call `super.init`. The `spyOn` is not possible to implement, because you need additional parameters to initialize the parent class.

A possible way to solve this is, that we don't need the `spyOn` at all when working with classes, because you have the class already instantiated. The `spyOn` is made primarily for protocols, because you might want to pass in a real implementation and just ensure it was called as expected. Mock created from a class already has this real implementation hiding in the parent class. So we might just add some switch that will enable passthrough to parent for every method. What do you think?

**Comment by TadeasKriz** [comment]
@bobbelkl I just got an idea how to workaround the `spyOn` problem, there will be a new commit shortly, I'll let you know when it'll be ready for testing.

**Comment by bobbelkl** [comment]
You're right, i forgot about `super.init` and everything it implies.
Very curious about your workaround. Looking forward too!

**Comment by TadeasKriz** [comment]
@bobbelkl Here it is, try the `4a2a72fac947e8ddd0d441d8b42ab964915d3b68` commit. To make a spying mock, do:
`let spyingMock = MockSomeClass(customInitParam: "XX").spy(on: realInstance)`. Please let me know if it work, thanks :)

**Comment by bobbelkl** [comment]
Great work
I like that one!

**Comment by krin-san** [comment]
@TadeasKriz, now the generator works fine with all examples I shown before.
Thanks!

**Comment by TadeasKriz** [comment]
Version 0.7.0 released! Yay!
