### ISSUE TITLE
No homebrew formula for cuckoo

### ISSUE THREAD

**Issue by michaelom** [SwiftKit/Cuckoo#69]
I tried to install the generator via homebrew and got the following message:

```
bash-3.2$ brew install cuckoo
Error: No available formula with the name "cuckoo" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

```

**Comment by TadeasKriz** [comment]
Hi, we don't use homebrew for Cuckoo anymore. It's building it itself when you use it in your project using CocoaPods.

**Comment by michaelom** [comment]
I see. 
Personally I'd rather generate the files outside my IDE (XCode/AppCode) than hooking the generator into the build lifecycle. Tooling should not be coupled to the IDE in my opinion. Also, bundling the generator with the mocking library makes importing Cuckoo somewhat cumbersome. I'll give it another try with CocoaPods.

Anyway, thanks for your quick reply.

**Comment by michaelom** [comment]
Hi again,
maybe your can update the project description. It still mentions the homebrew installation.

>>>Homebrew

Simply run brew install cuckoo and you are ready to go.

**Comment by TadeasKriz** [comment]
Using Cuckoo with CocoaPods is now much easier to do and it build new mocks each time you change the code so you don't need to remember running it manually. Of course some people like you might want to have more control over this. You can still run the generator outside of the IDE (just run the same script you'd run if you hooked it in Xcode as build script). Also we might look into having the homebrew support with the current project structure, it might be possible.

We merged the generator and runtime to single repository as it gives us much more control over updates and keeping the runtime and generator versions in sync.

Thanks abotu the info on brew install, I'll remove it from readme.
