### ISSUE TITLE
What is the relevance of spy in the sample code?

### ISSUE THREAD

**Issue by oliverfoggin** [SwiftKit/Cuckoo#7]
This isn't really an issue more of a question.

Anyway, in the sample code you create a spy variable using MockGenerator but then it isn't referenced again in the code.

Please could someone explain the relevance of this? Is it required?

Thanks

**Comment by TadeasKriz** [comment]
Cuckoo has two modes, mock and spy. The mock requires you to register every method you want to be callable. On the other hand, spy simply forwards all calls the the object you create the spy with. The point is to allow you alter just some methods, but keep the object responding as it is supposed to when calling others.

**Comment by oliverfoggin** [comment]
Ah ok, thanks :)
