### ISSUE TITLE
Xcode 8.1: Building CuckooGenerator fails due to a segmentation fault in SourceKittenFramework.

### ISSUE THREAD

**Issue by neilco** [SwiftKit/Cuckoo#71]
**Summary:**
------------

Building CuckooGenerator fails due to a segmentation fault in SourceKittenFramework. 

**Environment:** 
----------------

- Xcode 8.1
- Carthage 0.18.1

**Steps to Reproduce**
----------------------

1. Create a `Cartfile` containing the following:  

	```
	github "SwiftKit/Cuckoo" "ed32e76438593754892da5ced8073a9743080dd8”
	```  

2. In Terminal, run `carthage update --no-build`
3. Open `Carthage/Checkouts/Cuckoo/Cuckoo.xcworkspace` in Xcode 8.1
4. Change to the `CuckooGenerator` scheme
5. From the Xcode menu bar, select `Product -> Build`

**Expected Result**
-------------------

The CuckooGenerator build is successful. 

**Actual Result**
-----------------

The CuckooGenerator build fails due a compiler error with the SourceKittenFramework. Specifically, `File.swift` and `Request.swift` generate `Segmentation fault: 11` error. Xcode displays the following:

`Command failed due to Signal: Segmentation fault: 11`

**Additional Notes**
--------------------

See the following SourceKittenFramework issues:

- [Building `Request.swift` fails by crashing of Swift compiler on Xcode 8.1 GM seed](https://github.com/jpsim/SourceKitten/issues/282)
- [Building `File.swift` fails by crashing of Swift compiler on Xcode 8.1 GM seed](https://github.com/jpsim/SourceKitten/issues/280)

**Comment by neilco** [comment]
Updating SourceKitten to [867406c](https://github.com/jpsim/SourceKitten/commit/867406c54077fb8e700384774d4034cd4f926c06) resolves this issue.

**Comment by TadeasKriz** [comment]
Hi, thank you for the detailed report and a solution! I'll update the SourceKitten commit in our repository to fix this.
