### ISSUE TITLE
Xcode 8.1: Cuckoo build fails with duplicate symbol __TMRbBp error

### ISSUE THREAD

**Issue by neilco** [SwiftKit/Cuckoo#72]
**Summary:**
------------

Building Cuckoo fails with duplicate symbol error. 

**Environment:** 
----------------

- Xcode 8.1
- Carthage 0.18.1

**Steps to Reproduce**
----------------------

**Using Carthage:**

1. Create a `Cartfile` containing the following:  

	```
	github "SwiftKit/Cuckoo" "ed32e76438593754892da5ced8073a9743080dd8”
	```  

2. In Terminal, run `carthage update --platform ios`

**In Xcode:**

1. Open `Cuckoo.xcworkspace` in Xcode 8.1
2. Select the `Cuckoo` scheme
3. Edit the `Cuckoo` scheme to use the `Release` build configuration
4. From the Xcode menu bar, select `Product -> Build`

**Expected Result**
-------------------

The Cuckoo framework is built successfully. 

**Actual Result**
-----------------

The Cuckoo framework build fails due the following linker error:

```
duplicate symbol __TMRbBp in:
    .../Carthage/Checkouts/Cuckoo/DerivedData/Cuckoo/Build/Intermediates/Cuckoo.build/Release/Cuckoo.build/Objects-normal/x86_64/StubbingProxy.o
    .../Carthage/Checkouts/Cuckoo/DerivedData/Cuckoo/Build/Intermediates/Cuckoo.build/Release/Cuckoo.build/Objects-normal/x86_64/Matchable.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Additional Notes**
--------------------

This is a known issue in Xcode 8.1 ([SR-3081](https://bugs.swift.org/browse/SR-3081))

**Workaround for Carthage users:**

1. Open `Carthage/Checkouts/Cuckoo/Cuckoo.xcworkspace`. 
2. Change the `Reflection Metadata Level` build setting to `None` for the `Cuckoo` target in the `Cuckoo` project.
3. Run `carthage build --platform ios`

**Workaround for Xcode:**

1. Open `Cuckoo.xcworkspace` in Xcode 8.1
2. Select the `Cuckoo` scheme
3. Edit the `Cuckoo` scheme to use the `Release` build configuration
4. Change the `Reflection Metadata Level` build setting to `None` for the `Cuckoo` target in the `Cuckoo` project.
5. From the Xcode menu bar, select `Product -> Build`

**Comment by TadeasKriz** [comment]
Sounds like setting the `Reflection Metadata Level` to `None` in the project itself should fix this, right? However, does setting it to `None` have any implications? To be honest I never heard about this build setting and I'm not able to find more information on it.

**Comment by neilco** [comment]
I heard about it in [a comment on the Swift compiler issue](https://bugs.swift.org/browse/SR-3081?focusedCommentId=19373&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19373). With the build setting set to `None`, the framework build succeeds and all my tests using Cuckoo pass.

**Comment by TadeasKriz** [comment]
Ok, I'll set it in the project itself and add it to CocoaPods as I think the issue will be there as well.

**Comment by neilco** [comment]
Groovy. Thanks!

**Comment by TadeasKriz** [comment]
I've released `0.8.0` to CocoaPods with updated dependencies and some new fixes for Xcode 8.1. Please give it a go and let me know if it works properly for you. Thanks!

**Comment by salutis** [comment]
FYI: Tried to install `0.8.0` via Carthage and the problem still exists.

@neilco Thanks for the workaround!

**Comment by TadeasKriz** [comment]
@salutis @neilco Hi, I added the "Reflection metadata" to both the workspace and podspec file so it should work in both environments. Could you please give it a go (commit `c3e945f8c2833b475d33bc360d3c971f6b5f8c3f`) and let me know? Thanks!
