### ISSUE TITLE
How do I use the any<T>(type: T.Type = T.self) matcher?

### ISSUE THREAD

**Issue by cloudface** [SwiftKit/Cuckoo#75]
Hello. I apologise if this is a beginner's question but I can't figure out how to use the any<T> matcher in my unit test. I am trying to mock the following method using Cuckoo:

`func didLoadDataItem(item: DataItem)`

In my test I am trying to stub my mock as follows:
`let mockDelegate = MockSomeDelegate()
  stub(mockDelegate) { mock in
            when(mock.didLoadDataItem(any())) // Here is where I want to accept any DataItem instance
  }
 //Rest of test...`

How do I write this? I found examples on how to use the other matchers (anyInt(), anyString()) etc but I can't figure out how to do this with the matcher for a specific type. I'm still new to Swift and I haven't quite wrapped my head around Swift's typing mechanism just yet. Any help is appreciated.

Kind regards

**Comment by TadeasKriz** [comment]
Hi, using the `any()` does not work? What error does it give you?
