### ISSUE TITLE
Shell Script invocation error

### ISSUE THREAD

**Issue by Lubaba93** [SwiftKit/Cuckoo#77]
I am trying to build the application, but its displaying compile time error:

env: 8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode: No such file or directory
mv: rename Build/cuckoo_generator.app to cuckoo_generator.app: No such file or directory
/Users/sample/office-projects/project_name/Pods/Cuckoo/run: line 18: /Users/sample/office-projects/project_name/Pods/Cuckoo/Generator/cuckoo_generator.app/Contents/MacOS/cuckoo_generator: No such file or directory
Xcode :  8.0
Tag : 0.8.0

**Comment by MichaelChlubna** [comment]
Hi Lubaba,

could you please give me more info about this issue? Thnak you

**Comment by Lubaba93** [comment]
Here is the shell script I have added to Xcode:

# Define output file; change "${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name
OUTPUT_FILE="./SampleTests/GeneratedMocks.swift"
echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory; change "${PROJECT_NAME}" to your project's root source folder, if it's not the default name
INPUT_DIR="./Sample"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files; include as many input files as you'd like to create mocks for
${PODS_ROOT}/Cuckoo/run  generate --testable "Sample" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/Models/HomeScene/UserEntity.swift"


I am using the 0.8.0 version of Cuckoo with Xcode 8.0 and swift 3
While running the project I get the above 'Shell script invocation error'.
Please try to look into the issue
If I run the program without the shell script that I added to Xcode, it builds fine without any compile time errors

**Comment by Lubaba93** [comment]
Any updates @MichaelChlubna ??

**Comment by TadeasKriz** [comment]
Hi, I wasn't able to reproduce the issue. Could you try creating a new project and use Cuckoo in it and write exact steps that lead to the error? I tried creating a new project and integrating Cuckoo and it was working properly. Same with adding Cuckoo to existing project.

**Comment by Lubaba93** [comment]
Thanks for the info.
Tried with a new project but I am still facing the same issue.

Here are the screenshots for the podfile and the compile error:
![screen shot 2016-12-08 at 12 12 43 pm](https://cloud.githubusercontent.com/assets/15341649/21000267/df36d868-bd3f-11e6-826f-491a7d796a61.png)
![screen shot 2016-12-08 at 12 13 17 pm](https://cloud.githubusercontent.com/assets/15341649/21000268/df393932-bd3f-11e6-8c96-3b93306499fb.png)

Below is the shell script that I added to Xcode:
# Define output file; change "${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name
OUTPUT_FILE="./CuckooTrialTests/GeneratedMocks.swift"
echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory; change "${PROJECT_NAME}" to your project's root source folder, if it's not the default name
INPUT_DIR="./CuckooTrial"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files; include as many input files as you'd like to create mocks for
${PODS_ROOT}/Cuckoo/run generate --testable "CuckooTrial" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/ViewController.swift"
# ... and so forth

# After running once, locate `GeneratedMocks.swift` and drag it into your Xcode test target group

**Comment by TadeasKriz** [comment]
Try setting the `INPUT_DIR` so that it's an absolute path. For example you can use `$PROJECT_DIR` for directory of the project. So it might be `INPUT_DIR="$PROJECT_DIR/CuckooTrial"`. The same has to be applied to `OUTPUT_FILE`, so you can change it to `OUTPUT_FILE="$PROJECT_DIR/CuckooTrialTests/GeneratedMocks.swift"`.

Also, the last three lines need to either on the same line, or you have to add `\` at the end of them (except the last one), so that the new line is ignored when the script is run. It should look like this:
```
${PODS_ROOT}/Cuckoo/run generate --testable "CuckooTrial" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/ViewController.swift"
```

**Comment by Lubaba93** [comment]
Many Thanks. Its working
