### ISSUE TITLE
Build failed on swift-3.0 v0.7.0

### ISSUE THREAD

**Issue by bss-duy** [SwiftKit/Cuckoo#80]
Hi, firstly thanks for your work on this framework. I'd love to try it.

Unfortunately when i am trying to build the project, it failed on this 
mv: rename Build/cuckoo_generator.app to cuckoo_generator.app: No such file or directory

When i execute the 'run' file it got the same error.

I opened the CuckooGenerator.xcodeproj manually to build an app and it still this error:
Command failed due to signal : segmentation fault : 11 on Compile Request.swift

Any ideas on this one ?

Thanks.

**Comment by TadeasKriz** [comment]
Hi, please try updating to 0.8.1 (latest release) and see if it fixes the issue.

**Comment by bss-duy** [comment]
It worked perfectly. Thanks !
